---

  - name: Install Apache
    apt:
      name: apache2
      state: present
      update_cache: yes

  - name: Allow port 22/SSH
    iptables:
      chain: INPUT
      destination_port: "22"
      jump: ACCEPT
      protocol: tcp

  - name: Allow port 80/HTTP
    iptables:
      chain: INPUT
      destination_port: "80"
      jump: ACCEPT
      protocol: tcp

  - name: Allow port 443/HTTPS
    iptables:
      chain: INPUT
      destination_port: "443"
      jump: ACCEPT
      protocol: tcp

  - name: Allow established connections
    iptables:
      chain: INPUT
      ctstate: ESTABLISHED,RELATED
      jump: ACCEPT

  - name: Allow loopback traffic
    iptables:
      action: append
      chain: INPUT
      in_interface: lo
      jump: ACCEPT

  - name: Allow outgoing
    iptables:
      chain: OUTPUT
      jump: ACCEPT

  - name: Deny all incoming
    iptables:
      chain: INPUT
      jump: DROP